# Skip commits on updating git specific stuff. No actual project changes in this case so pointless to build.
skip_commits:
 files:
   - .gitignore
   - README.md

before_build:
  - nuget restore
after_build:
  - 7z a WolvenKit.zip %APPVEYOR_BUILD_FOLDER%\WolvenKit\bin\Debug\
  - appveyor PushArtifact WolvenKit.zip
# Update to the most recent VS.
image: Visual Studio 2017
configuration: Release
platform: Any CPU
